.PHONY: clean All

All:
	@echo "----------Building project:[ EJEMPLO10 - Debug ]----------"
	@cd "EJEMPLO10" && "$(MAKE)" -f  "EJEMPLO10.mk"
clean:
	@echo "----------Cleaning project:[ EJEMPLO10 - Debug ]----------"
	@cd "EJEMPLO10" && "$(MAKE)" -f  "EJEMPLO10.mk" clean
